sudo: false
language: python
python:
  - "3.8-dev"
  - "3.7"
  - "3.6"
  - "3.5.5"
  - "3.5.2"
  - "3.5.1"
  - "3.4"
  - "2.7"

install:
- pip install -r test-requirements.txt

script:
  - py.test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 --config=.flake8-tests test_typing_inspect.py; fi
